[program:rag-api]
command = /workspace/Garage/Simple\ RAG\ Books/my-rag-pipeline/run_api.sh
directory = /workspace/Garage/Simple\ RAG\ Books/my-rag-pipeline
user = root
autostart = true
autorestart = true
stopasgroup = true
killasgroup = true
stderr_logfile = /workspace/Garage/Simple\ RAG\ Books/my-rag-pipeline/supervisor.err.log
stdout_logfile = /workspace/Garage/Simple\ RAG\ Books/my-rag-pipeline/supervisor.out.log
stdout_logfile_maxbytes = 10MB
redirect_stderr = true
