[supervisord]
nodaemon=true
logfile=/workspace/supervisord.log
pidfile=/workspace/supervisord.pid

[unix_http_server]
file=/workspace/supervisor.sock

[supervisorctl]
serverurl=unix:///workspace/supervisor.sock

[program:rag-api]
command = bash "/workspace/Garage/Simple RAG Books/my-rag-pipeline/run_api.sh"
directory = "/workspace/Garage/Simple RAG Books/my-rag-pipeline"
user = root
autostart = true
autorestart = true
stopasgroup = true
killasgroup = true
stderr_logfile = /workspace/supervisor.err.log
stdout_logfile = /workspace/supervisor.out.log
stdout_logfile_maxbytes = 10MB
redirect_stderr = true
