[program:rag-api]
command = /home/mardonmashrabov/my-rag-pipeline/venv/bin/python /home/mardonmashrabov/my-rag-pipeline/serve_search_api.py
directory = /home/mardonmashrabov/my-rag-pipeline
user = mardonmashrabov
autostart = true
autorestart = true
stopasgroup = true
killasgroup = true
stdout_logfile = /home/mardonmashrabov/my-rag-pipeline/supervisor.out.log
stderr_logfile = /home/mardonmashrabov/my-rag-pipeline/supervisor.err.log
stdout_logfile_maxbytes = 10MB
redirect_stderr = true
environment = HOME="/home/mardonmashrabov"